# configuration for pi4
ServiceURL = "192.168.2.84:5551"
RootURLPattern = "/str/"
UseRelativeRoot = true
DebugVerbose = false
DBPath= "/home/igors/app/db/service-streamer.db"
TmpInfo= "/tmp"
VueLibName = "vue_prod.js"
StreamURL = "http://192.168.2.84:5550/stream.mp3"